version: '3.1'
services:
    client:
        build: './client'
        container_name: side-client
        volumes:
            - ./client:/app/client
        working_dir: '/app/client'
        command: 'yarn start'
        ports:
            - 127.00.1:3001:3000
